// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_input
void ui_input_screen_init(void);
lv_obj_t * ui_input;
lv_obj_t * ui_test_info;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_sample_ID_label;
lv_obj_t * ui_date_time_label;
lv_obj_t * ui_load_profile_label;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_sample_ID_textarea;
lv_obj_t * ui_date_time_textarea;
lv_obj_t * ui_load_profile_dropdown;
lv_obj_t * ui_load_profile_parameters;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Panel7;
lv_obj_t * ui_Label4;
lv_obj_t * ui_pattern1_up_timeout_textarea;
lv_obj_t * ui_pattern1_down_timeout_textarea;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Label5;
lv_obj_t * ui_pattern1_up_pwm_textarea;
lv_obj_t * ui_pattern1_down_pwm_textarea;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_Label6;
lv_obj_t * ui_pattern1_no_of_times_textarea;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label7;
lv_obj_t * ui_pattern1_up_condition_dropdown;
lv_obj_t * ui_pattern1_down_condition_dropdown;
lv_obj_t * ui_Panel12;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_Panel14;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Panel15;
lv_obj_t * ui_Label13;
lv_obj_t * ui_pattern2_up_timeout_textarea;
lv_obj_t * ui_pattern2_down_timeout_textarea;
lv_obj_t * ui_Panel16;
lv_obj_t * ui_Label14;
lv_obj_t * ui_pattern2_up_pwm_textarea;
lv_obj_t * ui_pattern2_down_pwm_textarea;
lv_obj_t * ui_Panel17;
lv_obj_t * ui_Label15;
lv_obj_t * ui_pattern2_no_of_times_textarea;
lv_obj_t * ui_Panel18;
lv_obj_t * ui_Label16;
lv_obj_t * ui_pattern2_up_condition_dropdown;
lv_obj_t * ui_pattern2_down_condition_dropdown;
lv_obj_t * ui_instruction;
lv_obj_t * ui_Label17;
lv_obj_t * ui_clear_all_label;
lv_obj_t * ui_run_label;
lv_obj_t * ui_background_decoration;
lv_obj_t * ui_Panel22;
lv_obj_t * ui_Panel23;
lv_obj_t * ui_Panel24;
lv_obj_t * ui_background_decoration1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel11;
lv_obj_t * ui_Panel19;

// SCREEN: ui_monitor
void ui_monitor_screen_init(void);
lv_obj_t * ui_monitor;
lv_obj_t * ui_test_info1;
lv_obj_t * ui_Panel27;
lv_obj_t * ui_sample_ID_label1;
lv_obj_t * ui_date_time_label1;
lv_obj_t * ui_load_profile_label1;
lv_obj_t * ui_Panel28;
lv_obj_t * ui_monitor_sample_ID_textarea;
lv_obj_t * ui_monitor_date_time_textarea;
lv_obj_t * ui_monitor_load_profile_textarea;
lv_obj_t * ui_instruction1;
lv_obj_t * ui_Label19;
lv_obj_t * ui_clear_all_button_label1;
lv_obj_t * ui_clear_all_button_label2;
lv_obj_t * ui_run_button_label1;
lv_obj_t * ui_test_output;
lv_obj_t * ui_Panel20;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Panel21;
lv_obj_t * ui_Panel25;
lv_obj_t * ui_Label20;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Panel26;
lv_obj_t * ui_number_of_cycles_label;
lv_obj_t * ui_status_label;
lv_obj_t * ui_motor_run_time_label;
lv_obj_t * ui_background_decoration2;
lv_obj_t * ui_Panel30;
lv_obj_t * ui_Panel31;
lv_obj_t * ui_Panel29;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_input_screen_init();
    ui_monitor_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_input);
}
