// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_input
void ui_input_screen_init(void);
extern lv_obj_t * ui_input;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Dropdown1;
// SCREEN: ui_monitor
void ui_monitor_screen_init(void);
extern lv_obj_t * ui_monitor;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
