// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_input
void ui_input_screen_init(void);
extern lv_obj_t * ui_input;
extern lv_obj_t * ui_test_info;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_sample_ID_label;
extern lv_obj_t * ui_date_time_label;
extern lv_obj_t * ui_load_profile_label;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_sample_ID_textarea;
extern lv_obj_t * ui_date_time_textarea;
extern lv_obj_t * ui_load_profile_dropdown;
extern lv_obj_t * ui_load_profile_parameters;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_pattern1_up_timeout_textarea;
extern lv_obj_t * ui_pattern1_down_timeout_textarea;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_pattern1_up_pwm_textarea;
extern lv_obj_t * ui_pattern1_down_pwm_textarea;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_pattern1_no_of_times_textarea;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_pattern1_up_condition_dropdown;
extern lv_obj_t * ui_pattern1_down_condition_dropdown;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_pattern2_up_timeout_textarea;
extern lv_obj_t * ui_pattern2_down_timeout_textarea;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_pattern2_up_pwm_textarea;
extern lv_obj_t * ui_pattern2_down_pwm_textarea;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_pattern2_no_of_times_textarea;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_pattern2_up_condition_dropdown;
extern lv_obj_t * ui_pattern2_down_condition_dropdown;
extern lv_obj_t * ui_instruction;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_clear_all_label;
extern lv_obj_t * ui_run_label;
extern lv_obj_t * ui_background_decoration;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_background_decoration1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel19;
// SCREEN: ui_monitor
void ui_monitor_screen_init(void);
extern lv_obj_t * ui_monitor;
extern lv_obj_t * ui_test_info1;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_sample_ID_label1;
extern lv_obj_t * ui_date_time_label1;
extern lv_obj_t * ui_load_profile_label1;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_monitor_sample_ID_textarea;
extern lv_obj_t * ui_monitor_date_time_textarea;
extern lv_obj_t * ui_monitor_load_profile_textarea;
extern lv_obj_t * ui_instruction1;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_clear_all_button_label1;
extern lv_obj_t * ui_clear_all_button_label2;
extern lv_obj_t * ui_run_button_label1;
extern lv_obj_t * ui_test_output;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_number_of_cycles_label;
extern lv_obj_t * ui_status_label;
extern lv_obj_t * ui_motor_run_time_label;
extern lv_obj_t * ui_background_decoration2;
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
