// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_input_screen_init(void)
{
    ui_input = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_input, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_input, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_input, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_test_info = lv_obj_create(ui_input);
    lv_obj_set_width(ui_test_info, lv_pct(60));
    lv_obj_set_height(ui_test_info, LV_SIZE_CONTENT);    /// 55
    lv_obj_set_x(ui_test_info, 2);
    lv_obj_set_y(ui_test_info, 2);
    lv_obj_set_flex_flow(ui_test_info, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_test_info, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_test_info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_test_info, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_test_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_test_info, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_test_info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_test_info, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_test_info, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_test_info, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_test_info, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_test_info, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_test_info);
    lv_obj_set_width(ui_Panel2, 70);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 26);
    lv_obj_set_y(ui_Panel2, -47);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sample_ID_label = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_sample_ID_label, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_height(ui_sample_ID_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sample_ID_label, 5);
    lv_obj_set_y(ui_sample_ID_label, 0);
    lv_obj_set_align(ui_sample_ID_label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_sample_ID_label, "Sample ID:");
    lv_obj_set_style_text_font(ui_sample_ID_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date_time_label = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_date_time_label, LV_SIZE_CONTENT);   /// 87
    lv_obj_set_height(ui_date_time_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date_time_label, 5);
    lv_obj_set_y(ui_date_time_label, 0);
    lv_obj_set_align(ui_date_time_label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_date_time_label, "Date & Time:");
    lv_obj_set_style_text_font(ui_date_time_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_load_profile_label = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_load_profile_label, LV_SIZE_CONTENT);   /// 65
    lv_obj_set_height(ui_load_profile_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_load_profile_label, 5);
    lv_obj_set_y(ui_load_profile_label, 0);
    lv_obj_set_align(ui_load_profile_label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_load_profile_label, "Load Profile:");
    lv_obj_set_style_text_font(ui_load_profile_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_test_info);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_width(ui_Panel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sample_ID_textarea = lv_textarea_create(ui_Panel3);
    lv_obj_set_width(ui_sample_ID_textarea, 110);
    lv_obj_set_height(ui_sample_ID_textarea, LV_SIZE_CONTENT);    /// 27
    lv_textarea_set_max_length(ui_sample_ID_textarea, 10);
    lv_textarea_set_placeholder_text(ui_sample_ID_textarea, "Numerical input only");
    lv_textarea_set_one_line(ui_sample_ID_textarea, true);
    lv_obj_clear_flag(ui_sample_ID_textarea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_sample_ID_textarea, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_sample_ID_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_sample_ID_textarea, lv_color_hex(0x808080),
                                LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sample_ID_textarea, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sample_ID_textarea, &lv_font_montserrat_10,
                               LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_date_time_textarea = lv_textarea_create(ui_Panel3);
    lv_obj_set_width(ui_date_time_textarea, 110);
    lv_obj_set_height(ui_date_time_textarea, LV_SIZE_CONTENT);    /// 27
    lv_textarea_set_max_length(ui_date_time_textarea, 20);
    lv_textarea_set_text(ui_date_time_textarea, "2023/08/28 03:25:05");
    lv_textarea_set_one_line(ui_date_time_textarea, true);
    lv_obj_clear_flag(ui_date_time_textarea, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(ui_date_time_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_date_time_textarea, &lv_font_montserrat_10,
                               LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_load_profile_dropdown = lv_dropdown_create(ui_Panel3);
    lv_dropdown_set_options(ui_load_profile_dropdown, "Default\nUser defined\nLoad profile X\nLoad profile Y");
    lv_obj_set_width(ui_load_profile_dropdown, 90);
    lv_obj_set_height(ui_load_profile_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_load_profile_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_load_profile_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_load_profile_dropdown, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_load_profile_dropdown), &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_load_profile_parameters = lv_obj_create(ui_input);
    lv_obj_set_height(ui_load_profile_parameters, 170);
    lv_obj_set_width(ui_load_profile_parameters, lv_pct(100));
    lv_obj_set_x(ui_load_profile_parameters, 0);
    lv_obj_set_y(ui_load_profile_parameters, 65);
    lv_obj_set_align(ui_load_profile_parameters, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_load_profile_parameters, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_load_profile_parameters, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_load_profile_parameters, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_load_profile_parameters);
    lv_obj_set_width(ui_Panel4, lv_pct(98));
    lv_obj_set_height(ui_Panel4, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Pattern 1:");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Panel4);
    lv_obj_set_width(ui_Panel5, lv_pct(100));
    lv_obj_set_height(ui_Panel5, LV_SIZE_CONTENT);    /// 79
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel6, 50);
    lv_obj_set_height(ui_Panel6, 65);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 30
    lv_label_set_text(ui_Label1, "Action\n");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel6);
    lv_obj_set_height(ui_Label2, 25);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 70
    lv_label_set_text(ui_Label2, "T_up_\npattern");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label3, "T_down\n_pattern");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Panel5);
    lv_obj_set_height(ui_Panel7, 65);
    lv_obj_set_width(ui_Panel7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label4, "T_timeout\n      (s)");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern1_up_timeout_textarea = lv_textarea_create(ui_Panel7);
    lv_obj_set_width(ui_pattern1_up_timeout_textarea, 50);
    lv_obj_set_height(ui_pattern1_up_timeout_textarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_pattern1_up_timeout_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern1_up_timeout_textarea, "10");
    lv_textarea_set_one_line(ui_pattern1_up_timeout_textarea, true);
    lv_obj_set_style_text_align(ui_pattern1_up_timeout_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern1_up_timeout_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern1_down_timeout_textarea = lv_textarea_create(ui_Panel7);
    lv_obj_set_width(ui_pattern1_down_timeout_textarea, 50);
    lv_obj_set_height(ui_pattern1_down_timeout_textarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_pattern1_down_timeout_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern1_down_timeout_textarea, "7");
    lv_textarea_set_one_line(ui_pattern1_down_timeout_textarea, true);
    lv_obj_set_style_text_align(ui_pattern1_down_timeout_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern1_down_timeout_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Panel5);
    lv_obj_set_height(ui_Panel8, 65);
    lv_obj_set_width(ui_Panel8, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label5, "PWM\n");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern1_up_pwm_textarea = lv_textarea_create(ui_Panel8);
    lv_obj_set_width(ui_pattern1_up_pwm_textarea, 50);
    lv_obj_set_height(ui_pattern1_up_pwm_textarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_pattern1_up_pwm_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern1_up_pwm_textarea, "100");
    lv_textarea_set_one_line(ui_pattern1_up_pwm_textarea, true);
    lv_obj_set_style_text_align(ui_pattern1_up_pwm_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern1_up_pwm_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern1_down_pwm_textarea = lv_textarea_create(ui_Panel8);
    lv_obj_set_width(ui_pattern1_down_pwm_textarea, 50);
    lv_obj_set_height(ui_pattern1_down_pwm_textarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_pattern1_down_pwm_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern1_down_pwm_textarea, "30");
    lv_textarea_set_one_line(ui_pattern1_down_pwm_textarea, true);
    lv_obj_set_style_text_align(ui_pattern1_down_pwm_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern1_down_pwm_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel5);
    lv_obj_set_height(ui_Panel9, 65);
    lv_obj_set_width(ui_Panel9, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel9, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 9);
    lv_label_set_text(ui_Label6, "Number\nof times");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern1_no_of_times_textarea = lv_textarea_create(ui_Panel9);
    lv_obj_set_width(ui_pattern1_no_of_times_textarea, 50);
    lv_obj_set_height(ui_pattern1_no_of_times_textarea, 22);
    lv_obj_set_align(ui_pattern1_no_of_times_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern1_no_of_times_textarea, "2");
    lv_obj_set_style_text_align(ui_pattern1_no_of_times_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern1_no_of_times_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Panel5);
    lv_obj_set_height(ui_Panel10, 65);
    lv_obj_set_width(ui_Panel10, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label7, "Stop\ncondition");
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern1_up_condition_dropdown = lv_dropdown_create(ui_Panel10);
    lv_dropdown_set_options(ui_pattern1_up_condition_dropdown, "Upper LS touched\nLower LS touched\nRun 1s");
    lv_dropdown_set_selected_highlight(ui_pattern1_up_condition_dropdown, false);
    lv_obj_set_width(ui_pattern1_up_condition_dropdown, 110);
    lv_obj_set_height(ui_pattern1_up_condition_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pattern1_up_condition_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pattern1_up_condition_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_pattern1_up_condition_dropdown, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_pattern1_up_condition_dropdown), &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern1_down_condition_dropdown = lv_dropdown_create(ui_Panel10);
    lv_dropdown_set_options(ui_pattern1_down_condition_dropdown, "Lower LS touched\nUpper LS touched\nRun 1s");
    lv_dropdown_set_selected_highlight(ui_pattern1_down_condition_dropdown, false);
    lv_obj_set_width(ui_pattern1_down_condition_dropdown, 110);
    lv_obj_set_height(ui_pattern1_down_condition_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pattern1_down_condition_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pattern1_down_condition_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_pattern1_down_condition_dropdown, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_pattern1_down_condition_dropdown), &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_load_profile_parameters);
    lv_obj_set_width(ui_Panel12, lv_pct(98));
    lv_obj_set_height(ui_Panel12, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel12, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Pattern 2:");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_Panel12);
    lv_obj_set_width(ui_Panel13, lv_pct(100));
    lv_obj_set_height(ui_Panel13, LV_SIZE_CONTENT);    /// 79
    lv_obj_set_flex_flow(ui_Panel13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Panel13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel14 = lv_obj_create(ui_Panel13);
    lv_obj_set_width(ui_Panel14, 50);
    lv_obj_set_height(ui_Panel14, 65);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel14, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel14, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label10, "Action\n");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel14);
    lv_obj_set_height(ui_Label11, 25);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 70
    lv_label_set_text(ui_Label11, "T_up_\npattern");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label12, "T_down\n_pattern");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_Panel13);
    lv_obj_set_height(ui_Panel15, 65);
    lv_obj_set_width(ui_Panel15, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel15, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel15, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label13, "T_timeout\n      (s)");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern2_up_timeout_textarea = lv_textarea_create(ui_Panel15);
    lv_obj_set_width(ui_pattern2_up_timeout_textarea, 50);
    lv_obj_set_height(ui_pattern2_up_timeout_textarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_pattern2_up_timeout_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern2_up_timeout_textarea, "2");
    lv_textarea_set_one_line(ui_pattern2_up_timeout_textarea, true);
    lv_obj_set_style_text_align(ui_pattern2_up_timeout_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern2_up_timeout_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern2_down_timeout_textarea = lv_textarea_create(ui_Panel15);
    lv_obj_set_width(ui_pattern2_down_timeout_textarea, 50);
    lv_obj_set_height(ui_pattern2_down_timeout_textarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_pattern2_down_timeout_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern2_down_timeout_textarea, "2");
    lv_textarea_set_one_line(ui_pattern2_down_timeout_textarea, true);
    lv_obj_set_style_text_align(ui_pattern2_down_timeout_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern2_down_timeout_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Panel13);
    lv_obj_set_height(ui_Panel16, 65);
    lv_obj_set_width(ui_Panel16, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel16, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel16, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label14, "PWM\n");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern2_up_pwm_textarea = lv_textarea_create(ui_Panel16);
    lv_obj_set_width(ui_pattern2_up_pwm_textarea, 50);
    lv_obj_set_height(ui_pattern2_up_pwm_textarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_pattern2_up_pwm_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern2_up_pwm_textarea, "20");
    lv_textarea_set_one_line(ui_pattern2_up_pwm_textarea, true);
    lv_obj_set_style_text_align(ui_pattern2_up_pwm_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern2_up_pwm_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern2_down_pwm_textarea = lv_textarea_create(ui_Panel16);
    lv_obj_set_width(ui_pattern2_down_pwm_textarea, 50);
    lv_obj_set_height(ui_pattern2_down_pwm_textarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_align(ui_pattern2_down_pwm_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern2_down_pwm_textarea, "20");
    lv_textarea_set_one_line(ui_pattern2_down_pwm_textarea, true);
    lv_obj_set_style_text_align(ui_pattern2_down_pwm_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern2_down_pwm_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_Panel13);
    lv_obj_set_height(ui_Panel17, 65);
    lv_obj_set_width(ui_Panel17, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel17, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel17, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 9);
    lv_label_set_text(ui_Label15, "Number\nof times");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern2_no_of_times_textarea = lv_textarea_create(ui_Panel17);
    lv_obj_set_width(ui_pattern2_no_of_times_textarea, 50);
    lv_obj_set_height(ui_pattern2_no_of_times_textarea, 22);
    lv_obj_set_align(ui_pattern2_no_of_times_textarea, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_pattern2_no_of_times_textarea, "4");
    lv_obj_set_style_text_align(ui_pattern2_no_of_times_textarea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pattern2_no_of_times_textarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_Panel13);
    lv_obj_set_height(ui_Panel18, 65);
    lv_obj_set_width(ui_Panel18, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel18, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel18, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label16, "Stop\ncondition");
    lv_obj_set_style_text_align(ui_Label16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern2_up_condition_dropdown = lv_dropdown_create(ui_Panel18);
    lv_dropdown_set_options(ui_pattern2_up_condition_dropdown, "Run 1s\nUpper LS touched\nLower LS touched");
    lv_dropdown_set_selected_highlight(ui_pattern2_up_condition_dropdown, false);
    lv_obj_set_width(ui_pattern2_up_condition_dropdown, 110);
    lv_obj_set_height(ui_pattern2_up_condition_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pattern2_up_condition_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pattern2_up_condition_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_pattern2_up_condition_dropdown, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_pattern2_up_condition_dropdown), &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pattern2_down_condition_dropdown = lv_dropdown_create(ui_Panel18);
    lv_dropdown_set_options(ui_pattern2_down_condition_dropdown, "Lower LS touched\nUpper LS touched\nRun 1s");
    lv_dropdown_set_selected_highlight(ui_pattern2_down_condition_dropdown, false);
    lv_obj_set_width(ui_pattern2_down_condition_dropdown, 110);
    lv_obj_set_height(ui_pattern2_down_condition_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pattern2_down_condition_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pattern2_down_condition_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_pattern2_down_condition_dropdown, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_pattern2_down_condition_dropdown), &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_instruction = lv_obj_create(ui_input);
    lv_obj_set_width(ui_instruction, 100);
    lv_obj_set_height(ui_instruction, 50);
    lv_obj_set_x(ui_instruction, -10);
    lv_obj_set_y(ui_instruction, 5);
    lv_obj_set_align(ui_instruction, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_instruction, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_instruction, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_instruction, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_instruction, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_instruction, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_instruction);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "INSTRUCTIONS:");
    lv_obj_set_style_text_decor(ui_Label17, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clear_all_label = lv_label_create(ui_instruction);
    lv_obj_set_width(ui_clear_all_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clear_all_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clear_all_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clear_all_label, "F1: Clear all");
    lv_obj_set_style_text_color(ui_clear_all_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_clear_all_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_clear_all_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clear_all_label, lv_color_hex(0xCF2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clear_all_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_run_label = lv_label_create(ui_instruction);
    lv_obj_set_width(ui_run_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_run_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_run_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_run_label, "F2: Run");
    lv_obj_set_style_text_color(ui_run_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_run_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_run_label, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_run_label, lv_color_hex(0x31B035), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_run_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_background_decoration = lv_obj_create(ui_input);
    lv_obj_set_width(ui_background_decoration, lv_pct(100));
    lv_obj_set_height(ui_background_decoration, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_background_decoration, 0);
    lv_obj_set_y(ui_background_decoration, 80);
    lv_obj_clear_flag(ui_background_decoration, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_background_decoration, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_background_decoration, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_background_decoration);
    lv_obj_set_height(ui_Panel22, 22);
    lv_obj_set_width(ui_Panel22, lv_pct(100));
    lv_obj_clear_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0xAFC1B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel23 = lv_obj_create(ui_background_decoration);
    lv_obj_set_height(ui_Panel23, 22);
    lv_obj_set_width(ui_Panel23, lv_pct(100));
    lv_obj_set_x(ui_Panel23, 0);
    lv_obj_set_y(ui_Panel23, 22);
    lv_obj_add_flag(ui_Panel23, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel23, lv_color_hex(0x22A3EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel23, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel24 = lv_obj_create(ui_background_decoration);
    lv_obj_set_height(ui_Panel24, 22);
    lv_obj_set_width(ui_Panel24, lv_pct(100));
    lv_obj_set_x(ui_Panel24, 0);
    lv_obj_set_y(ui_Panel24, 44);
    lv_obj_add_flag(ui_Panel24, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel24, lv_color_hex(0xDF791E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel24, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_background_decoration1 = lv_obj_create(ui_input);
    lv_obj_set_width(ui_background_decoration1, lv_pct(100));
    lv_obj_set_height(ui_background_decoration1, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_background_decoration1, 0);
    lv_obj_set_y(ui_background_decoration1, 170);
    lv_obj_clear_flag(ui_background_decoration1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_background_decoration1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_background_decoration1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_background_decoration1);
    lv_obj_set_height(ui_Panel1, 22);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xAFC1B5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_background_decoration1);
    lv_obj_set_height(ui_Panel11, 22);
    lv_obj_set_width(ui_Panel11, lv_pct(100));
    lv_obj_set_x(ui_Panel11, 0);
    lv_obj_set_y(ui_Panel11, 22);
    lv_obj_add_flag(ui_Panel11, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x22A3EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_background_decoration1);
    lv_obj_set_height(ui_Panel19, 22);
    lv_obj_set_width(ui_Panel19, lv_pct(100));
    lv_obj_set_x(ui_Panel19, 0);
    lv_obj_set_y(ui_Panel19, 44);
    lv_obj_add_flag(ui_Panel19, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel19, lv_color_hex(0xDF791E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel19, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

}
